/**
 * Builds the offline English spell-check lexicon from SCOWL (wordlist-english, sizes 10 → 50,
 * English + American + British variants so both spellings are accepted).
 * Output: src/data/content/spelling/lexicon.ts — a newline-separated string loaded lazily into a Set.
 *
 * Usage: npm run build:lexicon
 */
const fs = require('fs');
const path = require('path');

const SIZES = [10, 20, 35, 40, 50];
const VARIANTS = ['english', 'american', 'british'];

const words = new Set();
for (const variant of VARIANTS) {
  for (const size of SIZES) {
    const list = require(`wordlist-english/${variant}-words-${size}.json`);
    for (const w of list) {
      if (/^[a-z]+$/.test(w)) words.add(w);
    }
  }
}

const sorted = [...words].sort();
const out = `/* eslint-disable */
/**
 * AUTO-GENERATED by scripts/build-lexicon.js — do not edit by hand.
 * Source: SCOWL (Spell Checker Oriented Word Lists), Copyright 2000-2016 Kevin Atkinson.
 * Permission to use, copy, modify, distribute and sell these word lists is granted without fee.
 * ${sorted.length} lowercase entries.
 */
export const LEXICON = ${JSON.stringify(sorted.join('\n'))};
`;

const target = path.join(__dirname, '..', 'src', 'data', 'content', 'spelling', 'lexicon.ts');
fs.mkdirSync(path.dirname(target), { recursive: true });
fs.writeFileSync(target, out);
console.log(`Lexicon written: ${sorted.length} words → ${path.relative(process.cwd(), target)}`);
